Ep/be 150 risk manager constants
minterest-defi/minterest-chain-node pull request #44
Opened 2021-02-04 16:19 UTC by Apollo50

**Description:**

Add struct RiskManagerData. Set up storage for pallet risk-manager: map CurrencyId -> RiskManagerData
Add filed liquidation_attempts to PoolUserData struct. Impl getter && setter for this one.
For risk-manager pallet add admin's function to set params.
Add mock && test files for risk-manager paller. Impl tests for admin functions.
Fix all tests according to changes in struct PoolUserData
Impl template for liquidation process.

2021-02-05 11:48 UTC, lut1k commented on pallets/liquidity-pools/src/lib.rs
> +	pub liquidation_attempts: u32,
We don't need u32 for this parameter.
Enough u8.

2021-02-05 11:48 UTC, lut1k commented on pallets/liquidity-pools/src/lib.rs
> +	/// Also sets the global borrow_index to user interest index.u32
what is this?

2021-02-05 11:48 UTC, lut1k commented on pallets/liquidity-pools/src/lib.rs
> +	pub fn set_user_liquidation_attempts(who: &T::AccountId, pool_id: CurrencyId, new_count: u32) -> DispatchResult {
Maybe add a check <= max_attempts?
Add unit-test for this check.
There will be a cyclical dependence. Maybe add a max_attempts to the constants?

Maybe add two functions instead of this function:
"set_liquidation_attempts_to_zero()"
"take_away_one_liquidation_attempt()"

2021-02-05 11:48 UTC, lut1k commented on pallets/risk-manager/Cargo.toml
> +    'serde',
All crates are used in a [dependencies] must be in a std

2021-02-05 11:48 UTC, lut1k commented on pallets/risk-manager/src/lib.rs
> +		/// Set maximum amount of partial liquidation attempts..
remove on dot

2021-02-05 11:48 UTC, lut1k commented on pallets/liquidity-pools/src/tests.rs
> +			assert_ok!(TestPools::set_user_liquidation_attempts(&ALICE, CurrencyId::DOT, 15));
Attempt to set the parameter to 15 should raise an exception.

2021-02-05 11:48 UTC, lut1k commented on pallets/risk-manager/src/lib.rs
> +		pub fn set_max_attempts(origin, pool_id: CurrencyId, new_max_value: u32) -> DispatchResult {
may be u8 instead u32

2021-02-05 11:48 UTC, lut1k commented on pallets/risk-manager/src/lib.rs
> +		pub fn set_threshold(origin, pool_id: CurrencyId, new_threshold: Rate) -> DispatchResult {
Why did we use the numerator and denominator to set the Rate earlier?

2021-02-05 11:48 UTC, lut1k commented on pallets/risk-manager/src/lib.rs
> +		pub fn set_liquidation_fee(origin, pool_id: CurrencyId, new_liquidation_fee: Rate) -> DispatchResult {
see above

2021-02-05 12:09 UTC, Apollo50 commented on pallets/liquidity-pools/src/lib.rs
> +	pub fn set_user_liquidation_attempts(who: &T::AccountId, pool_id: CurrencyId, new_count: u32) -> DispatchResult {
For my view riskmanager pallet has to controle this parameter according to their constant, cause RiskManager responsible to liquidation logic and params value. In logic fn "liquidate" we will get this param & can set it to zero if it's needed.

2021-02-05 12:19 UTC, lut1k requested changes

2021-02-05 12:19 UTC, lut1k commented on pallets/risk-manager/src/lib.rs
> +			guard.extend_lock().map_err(|_| OffchainErr::OffchainLock)?;
May be implment with match <Controller<T>>::get_hypothetical_account_liquidity()  ?
Why print to the console "This member is absolutely clear!" ?
Why we use method unwrap() ? It causes panic

2021-02-05 13:01 UTC, Apollo50 commented on pallets/liquidity-pools/src/lib.rs
> +	pub liquidation_attempts: u32,
fixed

2021-02-05 13:02 UTC, Apollo50 commented on pallets/liquidity-pools/src/lib.rs
> +	/// Also sets the global borrow_index to user interest index.u32
fixed

2021-02-05 13:03 UTC, Apollo50 commented on pallets/liquidity-pools/src/lib.rs
> +	pub fn set_user_liquidation_attempts(who: &T::AccountId, pool_id: CurrencyId, new_count: u32) -> DispatchResult {
discussed*

2021-02-05 13:11 UTC, Apollo50 commented on pallets/risk-manager/Cargo.toml
> +    'serde',
fixed

2021-02-05 13:11 UTC, Apollo50 commented on pallets/liquidity-pools/src/tests.rs
> +			assert_ok!(TestPools::set_user_liquidation_attempts(&ALICE, CurrencyId::DOT, 15));
discussed*

2021-02-05 13:14 UTC, Apollo50 commented on pallets/risk-manager/src/lib.rs
> +		pub fn set_max_attempts(origin, pool_id: CurrencyId, new_max_value: u32) -> DispatchResult {
fixed

2021-02-05 13:28 UTC, Apollo50 commented on pallets/risk-manager/src/lib.rs
> +		/// Set maximum amount of partial liquidation attempts..
fixed

2021-02-08 08:51 UTC, lut1k approved these changes

2021-02-08 11:16 UTC, Pavel-Blaize commented on pallets/liquidity-pools/src/lib.rs
>  	/// Global borrow_index as of the most recent balance-changing action.
Please, upgrate pallet version, since we have storage change

2021-02-08 11:18 UTC, Pavel-Blaize approved these changes

2021-02-08 11:40 UTC, lut1k approved these changes

2021-02-08 12:32 UTC, merged